language: python
python:
  - 2.7

install:
  - pip install coveralls
  - pip install git+https://github.com/ThousandMileEye/eye.git

script:
  - coverage run setup.py test

after_success:
  - coverage html

notifications:
  slack: Tuntunkun:GAP5RRPPU

